# Generated by Django 4.0.4 on 2022-05-06 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquid',
            name='picture',
            field=models.URLField(default=None),
        ),
    ]
