# Generated by Django 4.0.4 on 2022-05-10 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_liquid_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquid',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
